### ISSUE TITLE
RuntimeError: Input and parameter tensors are not at the same device, found input tensor at cpu and parameter tensor at cuda:0

### ISSUE THREAD

**Issue by StockingYang** [MarWaltz/TUD_RL#21]
I modified the device option in MMGEnvRecDQN.yaml to cuda and run python -m tud_rl -t train -c MMGEnvRecDQN.yaml -a LSTMRecDQN.And there is a mistake happened.
![image](https://user-images.githubusercontent.com/38910621/202165431-57d4b411-0760-42ec-8454-ab342aa59ca1.png)

**Comment by MarWaltz** [comment]
Thanks for the report; is fixed.

Best,
Martin
